!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!C  PROGRAMA PARA GENERAR ARCHIVO DE ENTRADA PARA EL PROGRAMA DE ELEMENTOS    C
!C                   FINITOS DESARROLLADO POR JUAN CARLOS.                    C
!C                                                                            C
!C EL PROGRAMA SE ALIMENTA POR EL ARCHIVO *.msh GENERADO POR EL PROGRAMA GMSH C
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!C
!C
PROGRAM MALLAS
!
!
USE OMP_LIB
IMPLICIT NONE
!
!
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!    DECLARACIÓN DE VARIABLES
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!
!
INTEGER NP				!NÚMERO DE NODOS
INTEGER I, J, K, L, M, N, O, P
INTEGER NMEL
INTEGER NEL				!NÚMERO DE ELEMENTOS CÚBICOS
INTEGER NNAMES
INTEGER NPL
INTEGER NIMP

REAL*8, ALLOCATABLE, DIMENSION(:):: X, Y, Z
INTEGER, ALLOCATABLE, DIMENSION(:,:):: MIE
INTEGER, ALLOCATABLE, DIMENSION(:):: LOADEDVECS

REAL*8 elapsed_time
INTEGER tclock1, tclock2, clock_rate
call system_clock(tclock1)  ! start wall timer
!
!
OPEN(10,FILE='gmesh_files/Cubo2.msh')
READ(10,*)
READ(10,*)
READ(10,*)
READ(10,*)

READ(10,*) NNAMES        !NUMBER OF NODES.

DO I=1, NNAMES+2
	READ(10,*)
END DO

READ(10,*) NP        !NUMBER OF NODES.
!
ALLOCATE(X(NP), Y(NP), Z(NP))
!
X=0.0D0
Y=0.0D0
Z=0.0D0
!
DO I=1, NP
!
    READ(10,*) J, X(I), Y(I), Z(I)
!
END DO
!
READ(10,*)
READ(10,*)

READ(10,*) NMEL
NEL=0

DO I=1, NMEL
	READ(10,*) J, K
	IF (K==5) THEN
		NEL=NEL+1
	END IF
END DO

NMEL=NMEL-NEL

CLOSE(10)

X=X/100.0D0
Y=Y/100.0D0
Z=Z/100.0D0

OPEN(10,FILE='Coord.txt')

DO I=1, NP
	WRITE(10,'(3F10.4)') X(I), Y(I), Z(I)
END DO

CLOSE(10)

OPEN(10,FILE='Coord.txt')

DO I=1, NP
	READ(10,'(3F10.4)') X(I), Y(I), Z(I)
END DO

CLOSE(10, STATUS='DELETE')

NPL=0

O=0
DO I=1, NP
! 	IF(Z(I)==0.0D0 .AND. X(I)==0.0D0 .AND. Y(I)==0.0D0) THEN
	IF(Z(I)==0.0D0) THEN
		NPL=NPL+1
		O=I
	END IF
END DO

ALLOCATE(LOADEDVECS(NPL))
LOADEDVECS=0

O=0
DO I=1, NP
	IF(Z(I)==0.0D0) THEN
		O=O+1
		LOADEDVECS(O)=I
	END IF
END DO

NIMP=0

DO I=1, NP
	IF(Z(I)==0.0D0 .AND. X(I)==0.0D0 .AND. Y(I)==0.0D0) THEN
		NIMP=NIMP+1
		P=I
	END IF
END DO

OPEN(10,FILE='gmesh_files/Cubo2.msh')
READ(10,*)
READ(10,*)
READ(10,*)
READ(10,*)

READ(10,*)

DO I=1, NNAMES+2
	READ(10,*)
END DO

READ(10,*)
!
DO I=1, NP
!
    READ(10,*)
!
END DO
!
READ(10,*)
READ(10,*)

READ(10,*)

DO I=1, NMEL
	READ(10,*)
END DO

ALLOCATE(MIE(8,NEL))
MIE=0

DO I=1, NEL
	READ(10,*) J, K, L, M, N, MIE(:,I)
END DO

CLOSE(10)	
!
!
OPEN(10, FILE='../../Cubo2.inp')

WRITE(10,'(1A9)') 'Prueba 3D'

WRITE(10,'(3I8, 1F10.2, 8I7)') NP, NEL, 1, 1.50D0, 3001, 3, 8, 24, 5, 0, NPL, NIMP
WRITE(10,'(2I3)') 20, 4

DO I=1, NP
    IF (Z(I)==1.0D0) THEN
            WRITE(10, '(5I8, 3F10.4)') I, 3, 1, 1, 1, X(I), Y(I), Z(I)
        ELSE
            WRITE(10, '(5I8, 3F10.4)') I, 3, 0, 0, 0, X(I), Y(I), Z(I)
    END IF
END DO

WRITE(10, '(3I4, 5F10.2)') 1, 5, 0, 2.0D0, 1.0D0, 1.0D0, 0.0D0, 0.0D0






!1: TIPO DE ONDA, 1: P-WAVE, 2: S-WAVE
!2: TIEMPO TOTAL DE LA SEÑAL
!3: TIEMPO CENTRAL DEL PUSLO
!4: FRECUENCIA CARACTERISTICA DEL PULSO
!5: AMPLITUD DE LA SEÑAL
!6: ÁNGULO DE INCIDENCIA DE LA ONDA


WRITE(10, '(1I1, 1F7.2, 1F11.2, 3F17.2)') 2, 1.50D0, 0.25D0, 5.0D0, 10.00D0, 0.0D0

DO I=1, NEL
!
    WRITE(10,'(5I8, 8I8)') I, 6, 24, 1, 8, MIE(:,I)
!
END DO

! DO I=1, NP
! ! 	IF(Z(I)==0.0D0) THEN
! ! 		IF(X(I)==0.0D0) THEN
! ! 			IF(Y(I)==0.0D0) THEN
! ! 				WRITE(10,'(2I6)') I, 1
! ! 			END IF
! ! 		END IF
! !  	END IF
!  	IF (Z(I)==0.0D0) THEN
!  		WRITE(*,'(1I6, 3F12.6)') I, X(I), Y(I), Z(I)
!  	END IF
! END DO

! WRITE(10, '(2I8)') O, 3
DO I=1, NPL
	WRITE(10,'(2I8)') LOADEDVECS(I), 3
END DO

WRITE(10, '(1I8)') P

CLOSE(10)


call system_clock(tclock2, clock_rate)
elapsed_time = float(tclock2 - tclock1) / float(clock_rate)
print 11, elapsed_time
11 format("Elapsed time = ",f12.4, " seconds")

END PROGRAM MALLAS









































